# Generated by Django 5.1.3 on 2024-11-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_alter_trabajador_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueño',
            name='rol',
            field=models.CharField(default='Dueño', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='duracion_estimada',
            field=models.IntegerField(choices=[(30, '30 minutos'), (60, '1 hora'), (90, '1 hora y 30 minutos'), (120, '2 horas')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='garantia',
            field=models.CharField(choices=[('1 mes', '1 mes'), ('3 meses', '3 meses'), ('6 meses', '6 meses'), ('1 año', '1 año')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre_servicio',
            field=models.CharField(choices=[('Mantenimiento Preventivo', 'Mantenimiento Preventivo'), ('Cambio de Aceite', 'Cambio de Aceite'), ('Revisión de Frenos', 'Revisión de Frenos'), ('Alineación y Balanceo', 'Alineación y Balanceo'), ('Reparación de Motor', 'Reparación de Motor'), ('Diagnóstico Eléctrico', 'Diagnóstico Eléctrico')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(choices=[('bencina', 'Bencina'), ('diesel', 'Diésel'), ('electrico', 'Electrico'), ('etanol', 'Etanol'), ('gas', 'Gas'), ('hibrido', 'Híbrido'), ('hidrogeno', 'Hidrógeno'), ('otros', 'Otros')], max_length=50),
        ),
    ]
