# Generated by Django 5.1.2 on 2024-11-14 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_alter_dueño_rol_alter_servicio_duracion_estimada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener un formato válido, como 12.345.678-9', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[0-9Kk]$')]),
        ),
        migrations.AlterField(
            model_name='dueño',
            name='rut',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener un formato válido, como 12.345.678-9', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[0-9Kk]$')]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener un formato válido, como 12.345.678-9', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[0-9Kk]$')]),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='rut',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='El RUT debe tener un formato válido, como 12.345.678-9', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[0-9Kk]$')]),
        ),
    ]
