# Generated by Django 5.1.1 on 2024-10-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0010_proceso_vehiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='dispositivo_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
