# Generated by Django 5.1.1 on 2024-11-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0011_rename_first_name_customuser_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado_cita',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('pendiente', 'Pendiente'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=100),
        ),
    ]
