# Generated by Django 4.2 on 2024-11-03 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0012_alter_cita_estado_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dueño',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dueño', to='miapp.perfil'),
        ),
        migrations.AddField(
            model_name='dueño',
            name='rol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajador', to='miapp.perfil'),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('rut', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('disponibilidad', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('en_vacaciones', 'En Vacaciones')], max_length=50)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], max_length=20)),
                ('asignacion', models.CharField(choices=[('mecanico', 'Mecánico'), ('pintor', 'Pintor'), ('electrico', 'Eléctrico'), ('jefe_taller', 'Jefe de Taller')], max_length=50)),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='miapp.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('disponibilidad', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('en_vacaciones', 'En Vacaciones')], max_length=50)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], max_length=20)),
                ('asignacion', models.CharField(choices=[('mecanico', 'Mecánico'), ('pintor', 'Pintor'), ('electrico', 'Eléctrico'), ('jefe_taller', 'Jefe de Taller')], max_length=50)),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to='miapp.perfil')),
            ],
        ),
    ]
