# Generated by Django 4.2 on 2024-11-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0013_customuser_is_admin_customuser_is_superadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='notificaciones',
            field=models.ManyToManyField(blank=True, related_name='procesos', to='miapp.notificacion'),
        ),
    ]
