# Generated by Django 4.2 on 2024-11-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0014_alter_proceso_notificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='asignacion',
            field=models.CharField(choices=[('jefe_taller', 'Jefe de Taller')], max_length=50),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='asignacion',
            field=models.CharField(choices=[('supervisor', 'Supervisor')], max_length=50),
        ),
    ]
