# Generated by Django 4.2.16 on 2024-11-05 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0016_alter_pago_estado_pago_alter_pago_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.cotizacion'),
        ),
    ]
